### ISSUE TITLE
UserChrome.css Force width, max-width, min-width

### ISSUE THREAD

**Issue by benyaminl** [TRPB/pinstripe#1]
Seems your 
```css
#sidebar-box[sidebarcommand="_f9a7bfdd-59d9-4740-82e4-26232256236d_-sidebar-action"] #sidebar {
min-width: 0em !important;
}
```
Need to be changed to 
```css
#sidebar-box[sidebarcommand="_f9a7bfdd-59d9-4740-82e4-26232256236d_-sidebar-action"] #sidebar {
min-width: 0em !important;
max-width: 80px !important;
width: 80px !important;
}
```
